services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://mongo:27017/folgar
    depends_on:
      - mongo

volumes:
  mongo-data:
